spring.application.name=merchant-payment-portal
spring.datasource.url =jdbc://localhost:3306/merchant_payment_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

server.port=8080
